### ISSUE TITLE
Need to adapt to change in foreign_key_raw_id.html template

### ISSUE THREAD

**Issue by shaib** [sehmaschine/django-grappelli#1072]
In the move from Django 4 to Django 5, the `admin/widgets/foreign_key_raw_id.html` template added a wrapping of `{% if related_url %}<div>{% endif %}`...`{% if related_url %}</div>{% endif %}`. see https://github.com/django/django/commit/54e8b4e5825eadf94ad715459f3aa60df389c8d4.

In Grappelli, this causes a visual regression -- 

With Django 4 (and Grappelli 3.0.10):
<img width="325" height="41" alt="Image" src="https://github.com/user-attachments/assets/4b4fb036-c4ca-43fe-9f60-8024b5557d99" />

With Django 5 (and Grappelli 4.0.2):

<img width="325" height="55" alt="Image" src="https://github.com/user-attachments/assets/6609b709-ba84-406d-8a23-30d8c94bb13e" />

**Comment by shaib** [comment]
> I'm not able to reproduce this.

I'll try to make a minimal project

> We don't even have a "foreign_key_raw_id" template with grappelli.

That is part of the point -- since grappelli doesn't have this template, the one from Django is used; and that one changed in Django 5 in a way which breaks grappelli's CSS.

**Comment by sehmaschine** [comment]
@parsch Can you take a look pls?

**Comment by shaib** [comment]
Ok, sorry for not coming back so long...
I went to create the sample project, and only then I found out that the problem was more involved: It involves `django_extensions`. That is, when you just include a FK field in `raw_id_fields`, things are still ok. Things break when using `ForeignKeyAutocompleteAdmin` from django-extensions.

Now I'm not even sure in which project it should be fixed, if any...

Attaching the project anyway. It includes an initialized db with user admin/admin. Go to the "Pig" model in "Forky" app. The `pyproject.toml` is with `django<5` where things work, upgrade Django to break them.

[bug.tar.gz](https://github.com/user-attachments/files/24388522/bug.tar.gz)

**Comment by shaib** [comment]
I forgot an important note -- part of why I mistakenly thought that it was just the regular raw_id fields is that the workaround we found was to include the Django 4.2.x `foreign_key_raw_id.html` template in our project.

**Comment by shaib** [comment]
So, I've now done the obvious check, and indeed the breakage shows up in the vanilla admin, without Grappelli. So this appears to be a django-extensions issue.

**Comment by shaib** [comment]
Nope -- sorry for the noise, something must have gone wrong with my testing.

Without grappelli -- removing the package, and commenting out the lines in `settings.py` and `urls.py` -- this looks fine (Django 5.2.9):

<img width="1245" height="560" alt="Image" src="https://github.com/user-attachments/assets/3eabf3fd-bbcd-4186-aeab-3aa8b50c37a2" />

With grappelli:

<img width="1245" height="560" alt="Image" src="https://github.com/user-attachments/assets/de3e014f-3d94-468d-af92-43b27e64c78b" />

~~I don't seem to have permissions to reopen the issue; please do so -- unless you think this is out of scope, of course.~~

**Comment by sehmaschine** [comment]
I still don't understand the issue. You seem to have 2 (!) raw-id-fiels here, right? Can you please share your setup, because with just _one_ field, it looks ok.

**Comment by parsch** [comment]
@shaib Looking at the"Forky" app and upgrading it to Django 5.0 the rendered HTML of that widget looks like 

```
<div class="grp-related-widget-wrapper related-widget-wrapper">
    <div class="grp-related-widget">
        <input type="text" id="lookup_owner" value="admin" style="" autocomplete="off" class="acInput">
        <a href="/admin/auth/user/?_to_field=id" class="related-lookup" id="lookup_id_owner" onclick="return showRelatedObjectLookupPopup(this);"></a>
        <script type="text/javascript"></script>
        <div>
            <input type="text" name="owner" value="1" data-context="available-source" required="" aria-describedby="id_owner_helptext" id="id_owner" class="vForeignKeyRawIdAdminField">
            <a href="/admin/auth/user/?_to_field=id" class="related-lookup" id="lookup_id_owner" title="Lookup"></a>
            <strong><a href="/admin/auth/user/1/change/">admin</a></strong>
        </div>
    </div>
    <ul class="grp-tools grp-related-widget-tools"></ul>
</div>
```

I don't see any possibility to identify your case with the two inputs contained in one widget in order to apply any styling to improve the layout. If you have any idea, please let me know.

**Comment by shaib** [comment]
Thanks @parsch 

The parallel from django 4 (with comments added) is
```html
<div class="grp-related-widget-wrapper related-widget-wrapper">
    <div class="grp-related-widget">
        <input type="text" id="lookup_owner" value="admin" style="" autocomplete="off" class="acInput">
        <a href="/admin/auth/user/?_to_field=id" class="related-lookup" id="lookup_id_owner" onclick="return showRelatedObjectLookupPopup(this);"></a>
        <script type="text/javascript"></script>
        <!-- <div> added here in Django 5 -->
            <input type="text" name="owner" value="1" required id="id_owner" class="vForeignKeyRawIdAdminField">
            <a href="/admin/auth/user/?_to_field=id" class="related-lookup" id="lookup_id_owner" title="Lookup"></a>
            <strong><a href="/admin/auth/user/1/change/">admin</a></strong>
        <!-- </div> added here in Django 5 -->
    </div>
    <ul class="grp-tools grp-related-widget-tools"></ul>
</div>
```
So I'm guessing if we can catch this added `div` and give it `display: inline` it would fix things. Of course, I don't know what other things this would break.

**Comment by shaib** [comment]
I mean, we could try something along the lines of
```css
/*
 * django-grappelli/grappelli/sass/partials/layout/_tools.scss
 * near line 304
 */

.grp-related-widget-wrapper {
    position: relative;
    float: left;
    display: flex;
    
    .grp-related-widget > div {
        display: inline-block;       
    }
}
```

Or maybe even, to be very specific, something like

```css
/*
 * django-grappelli/grappelli/sass/partials/layout/_tools.scss
 * near line 304
 */

.grp-related-widget-wrapper {
    position: relative;
    float: left;
    display: flex;
    
    .grp-related-widget > div:has(> input + a) {
        display: inline-block;       
    }
}
```

**Comment by parsch** [comment]
@shaib Thanks for coming up with a suggestion, I tested it briefly and think the 2nd version does the trick without interfering with other possible layouts.

**Comment by shaib** [comment]
@parsch Thanks a bunch! I just tested the original project with the current `stable/4.0.x`, removing the workarounds we installed, and it works well.
